name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged
        ports:
          - 5432:5432
          - 27017:27017
          - 2181:2181
          - 9092:9092
          - 7077:7077
          - 8080:8080
          - 8081:8081
          - 8000:8000
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: docker-compose up -d

      - name: Wait for services to be ready
        run: sleep 30

      - name: Run JMeter Tests
        run: docker-compose run --rm jmeter

      - name: Check JMeter Results
        run: |
          if grep -q "FAIL" jmeter/results/results.jtl; then
            echo "JMeter tests failed"
            exit 1
          fi
