version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: education_postgres
    environment:
      POSTGRES_DB: education_db
      POSTGRES_USER: edu_user
      POSTGRES_PASSWORD: securepassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../../databases/postgresql/scripts:/docker-entrypoint-initdb.d
    networks:
      - education_network

volumes:
  postgres_data:

networks:
  education_network:
    driver: bridge
